name: handtrack_mobile
description: HandTrack enterprise mobile starter (Flutter).
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  handtrack_engine:
    path: ../../engine/flutter_plugin/handtrack_engine
  shared_preferences: ^2.2.3
  google_mobile_ads: ^5.1.0
  share_plus: any
  speech_to_text: any
  flutter_tts: any
  path_provider: any
  screenshot: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
